import type { Metadata } from "next";
import { Nanum_Myeongjo } from "next/font/google";

import MswProvider from "@/mocks/MswProvider";

import "./globals.css";

const nanumMyeongjo = Nanum_Myeongjo({
  subsets: ["latin"],
  weight: ["400", "700", "800"],
  variable: "--font-myeongjo",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={`${nanumMyeongjo.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <MswProvider>{children}</MswProvider>
      </body>
    </html>
  );
}
